version: "3.8"

services:
  database:
    container_name: fablabDB
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: fablab_db
      MYSQL_USER: fablab_user
      MYSQL_PASSWORD: fablab_pwd
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: fablabPHP
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/fablab_project
    depends_on:
      - database

  nginx:
    container_name: fablab_server
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/fablab_project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database
